spring.data.mongodb.uri=mongodb+srv://bikashsah891_db_user:dERVecCt1Zcgph75@cluster0.e3a5tqc.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=SynCoreDataBase
spring.data.mongodb.auto-index-creation=true